UPDATE PERSON
SET IMAGE_URL = '2.JPG'
WHERE PERSONID = 2;
UPDATE PERSON
SET IMAGE_URL = '3.JPG'
WHERE PERSONID = 3;
UPDATE PERSON
SET IMAGE_URL = '4.JPG'
WHERE PERSONID = 4;
UPDATE PERSON
SET IMAGE_URL = '5.JPG'
WHERE PERSONID = 5;
UPDATE PERSON
SET IMAGE_URL = '6.JPG'
WHERE PERSONID = 6;
UPDATE PERSON
SET IMAGE_URL = '7.JPG'
WHERE PERSONID = 7;
UPDATE PERSON
SET IMAGE_URL = '8.JPG'
WHERE PERSONID = 8;
UPDATE PERSON
SET IMAGE_URL = '9.JPG'
WHERE PERSONID = 9;
UPDATE PERSON
SET IMAGE_URL = '10.JPG'
WHERE PERSONID = 10;
UPDATE PERSON
SET IMAGE_URL = '11.JPG'
WHERE PERSONID = 11;
UPDATE PERSON
SET IMAGE_URL = '12.JPG'
WHERE PERSONID = 12;
UPDATE PERSON
SET IMAGE_URL = '13.JPG'
WHERE PERSONID = 13;
UPDATE PERSON
SET IMAGE_URL = '14.JPG'
WHERE PERSONID = 14;
UPDATE PERSON
SET IMAGE_URL = '15.JPG'
WHERE PERSONID = 15;
UPDATE PERSON
SET IMAGE_URL = '16.JPG'
WHERE PERSONID = 16;
UPDATE PERSON
SET IMAGE_URL = '17.JPG'
WHERE PERSONID = 17;
UPDATE PERSON
SET IMAGE_URL = '18.JPG'
WHERE PERSONID = 18;
UPDATE PERSON
SET IMAGE_URL = '19.JPG'
WHERE PERSONID = 19;
UPDATE PERSON
SET IMAGE_URL = '20.JPG'
WHERE PERSONID = 20;
UPDATE PERSON
SET IMAGE_URL = '21.JPG'
WHERE PERSONID = 21;
UPDATE PERSON
SET IMAGE_URL = '22.JPG'
WHERE PERSONID = 22;
UPDATE PERSON
SET IMAGE_URL = '23.JPG'
WHERE PERSONID = 23;
UPDATE PERSON
SET IMAGE_URL = '24.JPG'
WHERE PERSONID = 24;
UPDATE PERSON
SET IMAGE_URL = '25.JPG'
WHERE PERSONID = 25;
UPDATE PERSON
SET IMAGE_URL = '26.JPG'
WHERE PERSONID = 26;
UPDATE PERSON
SET IMAGE_URL = '27.JPG'
WHERE PERSONID = 27;
UPDATE PERSON
SET IMAGE_URL = '28.JPG'
WHERE PERSONID = 28;
UPDATE PERSON
SET IMAGE_URL = '29.JPG'
WHERE PERSONID = 29;
UPDATE PERSON
SET IMAGE_URL = '30.JPG'
WHERE PERSONID = 30;
UPDATE PERSON
SET IMAGE_URL = '31.JPG'
WHERE PERSONID = 31;
UPDATE PERSON
SET IMAGE_URL = '32.JPG'
WHERE PERSONID = 32;
UPDATE PERSON
SET IMAGE_URL = '33.JPG'
WHERE PERSONID = 33;
UPDATE PERSON
SET IMAGE_URL = '34.JPG'
WHERE PERSONID = 34;
UPDATE PERSON
SET IMAGE_URL = '35.JPG'
WHERE PERSONID = 35;
UPDATE PERSON
SET IMAGE_URL = '36.JPG'
WHERE PERSONID = 36;
UPDATE PERSON
SET IMAGE_URL = '37.JPG'
WHERE PERSONID = 37;
UPDATE PERSON
SET IMAGE_URL = '38.JPG'
WHERE PERSONID = 38;
UPDATE PERSON
SET IMAGE_URL = '39.JPG'
WHERE PERSONID = 39;
UPDATE PERSON
SET IMAGE_URL = '40.JPG'
WHERE PERSONID = 40;
UPDATE PERSON
SET IMAGE_URL = '41.JPG'
WHERE PERSONID = 41;
UPDATE PERSON
SET IMAGE_URL = '42.JPG'
WHERE PERSONID = 42;
UPDATE PERSON
SET IMAGE_URL = '43.JPG'
WHERE PERSONID = 43;
UPDATE PERSON
SET IMAGE_URL = '44.JPG'
WHERE PERSONID = 44;
UPDATE PERSON
SET IMAGE_URL = '45.JPG'
WHERE PERSONID = 45;
UPDATE PERSON
SET IMAGE_URL = '46.JPG'
WHERE PERSONID = 46;
UPDATE PERSON
SET IMAGE_URL = '47.JPG'
WHERE PERSONID = 47;
UPDATE PERSON
SET IMAGE_URL = '48.JPG'
WHERE PERSONID = 48;
UPDATE PERSON
SET IMAGE_URL = '49.JPG'
WHERE PERSONID = 49;
UPDATE PERSON
SET IMAGE_URL = '50.JPG'
WHERE PERSONID = 50;
UPDATE PERSON
SET IMAGE_URL = '51.JPG'
WHERE PERSONID = 51;
UPDATE PERSON
SET IMAGE_URL = '52.JPG'
WHERE PERSONID = 52;
UPDATE PERSON
SET IMAGE_URL = '53.JPG'
WHERE PERSONID = 53;
UPDATE PERSON
SET IMAGE_URL = '54.JPG'
WHERE PERSONID = 54;
UPDATE PERSON
SET IMAGE_URL = '55.JPG'
WHERE PERSONID = 55;
UPDATE PERSON
SET IMAGE_URL = '56.JPG'
WHERE PERSONID = 56;
UPDATE PERSON
SET IMAGE_URL = '57.JPG'
WHERE PERSONID = 57;
UPDATE PERSON
SET IMAGE_URL = '58.JPG'
WHERE PERSONID = 58;
UPDATE PERSON
SET IMAGE_URL = '59.JPG'
WHERE PERSONID = 59;
UPDATE PERSON
SET IMAGE_URL = '60.JPG'
WHERE PERSONID = 60;
UPDATE PERSON
SET IMAGE_URL = '61.JPG'
WHERE PERSONID = 61;
UPDATE PERSON
SET IMAGE_URL = '62.JPG'
WHERE PERSONID = 62;
UPDATE PERSON
SET IMAGE_URL = '63.JPG'
WHERE PERSONID = 63;
UPDATE PERSON
SET IMAGE_URL = '64.JPG'
WHERE PERSONID = 64;
UPDATE PERSON
SET IMAGE_URL = '65.JPG'
WHERE PERSONID = 65;
UPDATE PERSON
SET IMAGE_URL = '66.JPG'
WHERE PERSONID = 66;
UPDATE PERSON
SET IMAGE_URL = '67.JPG'
WHERE PERSONID = 67;
UPDATE PERSON
SET IMAGE_URL = '68.JPG'
WHERE PERSONID = 68;
UPDATE PERSON
SET IMAGE_URL = '69.JPG'
WHERE PERSONID = 69;
UPDATE PERSON
SET IMAGE_URL = '70.JPG'
WHERE PERSONID = 70;
UPDATE PERSON
SET IMAGE_URL = '71.JPG'
WHERE PERSONID = 71;
UPDATE PERSON
SET IMAGE_URL = '72.JPG'
WHERE PERSONID = 72;
UPDATE PERSON
SET IMAGE_URL = '73.JPG'
WHERE PERSONID = 73;
UPDATE PERSON
SET IMAGE_URL = '74.JPG'
WHERE PERSONID = 74;
UPDATE PERSON
SET IMAGE_URL = '75.JPG'
WHERE PERSONID = 75;
UPDATE PERSON
SET IMAGE_URL = '76.JPG'
WHERE PERSONID = 76;
UPDATE PERSON
SET IMAGE_URL = '77.JPG'
WHERE PERSONID = 77;
UPDATE PERSON
SET IMAGE_URL = '78.JPG'
WHERE PERSONID = 78;
UPDATE PERSON
SET IMAGE_URL = '79.JPG'
WHERE PERSONID = 79;
UPDATE PERSON
SET IMAGE_URL = '80.JPG'
WHERE PERSONID = 80;
UPDATE PERSON
SET IMAGE_URL = '81.JPG'
WHERE PERSONID = 81;
UPDATE PERSON
SET IMAGE_URL = '82.JPG'
WHERE PERSONID = 82;
UPDATE PERSON
SET IMAGE_URL = '83.JPG'
WHERE PERSONID = 83;
UPDATE PERSON
SET IMAGE_URL = '84.JPG'
WHERE PERSONID = 84;
UPDATE PERSON
SET IMAGE_URL = '85.JPG'
WHERE PERSONID = 85;
UPDATE PERSON
SET IMAGE_URL = '86.JPG'
WHERE PERSONID = 86;
UPDATE PERSON
SET IMAGE_URL = '87.JPG'
WHERE PERSONID = 87;
UPDATE PERSON
SET IMAGE_URL = '88.JPG'
WHERE PERSONID = 88;
UPDATE PERSON
SET IMAGE_URL = '89.JPG'
WHERE PERSONID = 89;
UPDATE PERSON
SET IMAGE_URL = '90.JPG'
WHERE PERSONID = 90;
UPDATE PERSON
SET IMAGE_URL = '91.JPG'
WHERE PERSONID = 91;
UPDATE PERSON
SET IMAGE_URL = '92.JPG'
WHERE PERSONID = 92;
UPDATE PERSON
SET IMAGE_URL = '93.JPG'
WHERE PERSONID = 93;
UPDATE PERSON
SET IMAGE_URL = '94.JPG'
WHERE PERSONID = 94;
UPDATE PERSON
SET IMAGE_URL = '95.JPG'
WHERE PERSONID = 95;
UPDATE PERSON
SET IMAGE_URL = '96.JPG'
WHERE PERSONID = 96;
UPDATE PERSON
SET IMAGE_URL = '97.JPG'
WHERE PERSONID = 97;
UPDATE PERSON
SET IMAGE_URL = '98.JPG'
WHERE PERSONID = 98;
UPDATE PERSON
SET IMAGE_URL = '99.JPG'
WHERE PERSONID = 99;
UPDATE PERSON
SET IMAGE_URL = '100.JPG'
WHERE PERSONID = 100;
UPDATE PERSON
SET IMAGE_URL = '101.JPG'
WHERE PERSONID = 101;
UPDATE PERSON
SET IMAGE_URL = '102.JPG'
WHERE PERSONID = 102;
UPDATE PERSON
SET IMAGE_URL = '103.JPG'
WHERE PERSONID = 103;
UPDATE PERSON
SET IMAGE_URL = '104.JPG'
WHERE PERSONID = 104;
UPDATE PERSON
SET IMAGE_URL = '105.JPG'
WHERE PERSONID = 105;
UPDATE PERSON
SET IMAGE_URL = '106.JPG'
WHERE PERSONID = 106;
UPDATE PERSON
SET IMAGE_URL = '107.JPG'
WHERE PERSONID = 107;
UPDATE PERSON
SET IMAGE_URL = '108.JPG'
WHERE PERSONID = 108;
UPDATE PERSON
SET IMAGE_URL = '109.JPG'
WHERE PERSONID = 109;
UPDATE PERSON
SET IMAGE_URL = '110.JPG'
WHERE PERSONID = 110;
UPDATE PERSON
SET IMAGE_URL = '111.JPG'
WHERE PERSONID = 111;
UPDATE PERSON
SET IMAGE_URL = '112.JPG'
WHERE PERSONID = 112;
UPDATE PERSON
SET IMAGE_URL = '113.JPG'
WHERE PERSONID = 113;
UPDATE PERSON
SET IMAGE_URL = '114.JPG'
WHERE PERSONID = 114;
UPDATE PERSON
SET IMAGE_URL = '115.JPG'
WHERE PERSONID = 115;
UPDATE PERSON
SET IMAGE_URL = '116.JPG'
WHERE PERSONID = 116;
UPDATE PERSON
SET IMAGE_URL = '117.JPG'
WHERE PERSONID = 117;
UPDATE PERSON
SET IMAGE_URL = '118.JPG'
WHERE PERSONID = 118;
