UPDATE venue
SET IMAGEURL = '500.jpg'
WHERE VENUE_ID = 1;
UPDATE venue
SET IMAGEURL = '501.jpg'
WHERE VENUE_ID = 2;
UPDATE venue
SET IMAGEURL = '502.jpg'
WHERE VENUE_ID = 3;
UPDATE venue
SET IMAGEURL = '503.jpg'
WHERE VENUE_ID = 4;
UPDATE venue
SET IMAGEURL = '504.jpg'
WHERE VENUE_ID = 5;
UPDATE venue
SET IMAGEURL = '505.jpg'
WHERE VENUE_ID = 6;
UPDATE venue
SET IMAGEURL = '506.jpg'
WHERE VENUE_ID = 7;
UPDATE venue
SET IMAGEURL = '507.jpg'
WHERE VENUE_ID = 8;
UPDATE venue
SET IMAGEURL = '508.jpg'
WHERE VENUE_ID = 9;
